// <auto-generated />
namespace Student_Management_Sysytem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tblEnroll1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblEnroll1));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210916581_tblEnroll1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
